-- StoreByMari presentation override for AppByMari product images.
-- The source image remains sync-owned; this column survives future syncs.
--
-- The migration runner checks INFORMATION_SCHEMA before issuing the ALTER so
-- this migration remains compatible with MySQL/MariaDB versions that do not
-- support ALTER TABLE ... ADD COLUMN IF NOT EXISTS.
